Use "web_extra_daemons"
tyler36/ddev-laravel-queue pull request #11
Opened 2024-04-25 03:14 UTC by tyler36

This PR upgrades this addon to use "web_extra_daemons" to start the queue worker.

This has the benefits of

- simplifying config
- does not break container if supervisor crashes

2024-04-25 03:32 UTC, rfay commented
Because in DDEV v1.23.0, web_extra_daemons failing don't bring down the container:

* Consider adding a .ddev/config.ddev-laravel-queue.yaml with `ddev_version_constraint: v1.23.0`, which will make sure that  people get this behavior
* Consider wrapping the queue runner with a `while true; do <run queue> || true; done` so that the queue exiting doesn't end up with no runner. 

And thanks!

2024-04-25 03:38 UTC, rfay requested changes
Some ideas!

2024-04-25 03:38 UTC, rfay commented on config.laravel-workers.yaml
> +    command: "/usr/bin/php /var/www/html/artisan queue:work --sleep=3 --tries=3"
Add a `while true; do` wrapper here so this will keep going even if it fails. Maybe add a sleep 1 in the loop to slow it down if it's misconfigured.

2024-04-25 03:38 UTC, rfay commented on config.laravel-workers.yaml
> +#ddev-generated
```suggestion
#ddev-generated

ddev_version_constraint: '>=v1.23.0'
```

2024-04-25 03:38 UTC, rfay commented on config.laravel-workers.yaml
> +    command: "/usr/bin/php /var/www/html/artisan queue:work --sleep=3 --tries=3"
```suggestion
    command: bash -c "while true; do /usr/bin/php /var/www/html/artisan queue:work --sleep=3 --tries=3; sleep 1; done"
```

2024-04-25 03:54 UTC, tyler36 commented on config.laravel-workers.yaml
> +    command: "/usr/bin/php /var/www/html/artisan queue:work --sleep=3 --tries=3"
This is cause the tests to fail when starting the project:

```
# Unable to start web_extra_daemons using supervisorctl, stdout=webextradaemons:queue-1: ERROR (spawn error)
# , stderr=: composeCmd failed to run 'COMPOSE_PROJECT_NAME=ddev-test-laravel-queue docker-compose -f /home/runner/tmp/test-laravel-queue/.ddev/.ddev-docker-compose-full.yaml exec -T web bash -c set -eu && ( supervisorctl start webextradaemons:*)', action='[exec -T web bash -c set -eu && ( supervisorctl start webextradaemons:*)]', err='exit status 7', stdout='webextradaemons:queue-1: ERROR (spawn error)
# ', stderr=''
```

2024-04-25 08:47 UTC, tyler36 commented on config.laravel-workers.yaml
> +    command: "/usr/bin/php /var/www/html/artisan queue:work --sleep=3 --tries=3"
The tests are passing (with the exception of "release") with the code below. Does this have the same effect?

```yml
 command: "while true; do /usr/bin/php /var/www/html/artisan queue:work --sleep=3 --tries=3; sleep 1; done"
```

2024-04-25 14:50 UTC, rfay commented on config.laravel-workers.yaml
> +    command: "/usr/bin/php /var/www/html/artisan queue:work --sleep=3 --tries=3"
I'm not sure the `command` can be a bash script unless you invoke bash, but you can try it. 

For release, you can temporarily comment out the release test as you know, then enable after release.

2024-04-26 00:25 UTC, tyler36 commented
This implementation removes some files. Do we need to add something that removes them or is that handled automatically?

2024-04-26 03:08 UTC, rfay commented
To remove files, you probably want to do it with the pre_install_actions, post_install_actions, or removal_actions, all of which take bash commands. Make sure you don't remove files that don't have #ddev-generated in them.

```
if grep "#ddev-generated" <file>; then rm <file>; fi
```

2024-05-10 16:29 UTC, rfay commented
Testing with
```
ddev get https://github.com/tyler36/ddev-laravel-queue/tarball/10-Consider-migrating-to-web_extra_daemons
```

2024-05-10 16:35 UTC, rfay commented
When I install I see
```
Executing post-install actions:
grep: web-build/Dockerfile.ddev-laravel-worker: No such file or directory

grep: web-build/laravel-worker.conf: No such file or directory
```

The grep should have `2>/dev/null` on it probably.

2024-05-10 16:38 UTC, rfay approved these changes
Looks great to me. After installing this, I see this in the web container:

```
$ ps -ef | grep queue
rfay        2198     114  0 16:36 ?        00:00:00 bash -c while true; do /usr/bin/php /var/www/html/artisan queue:work --sleep
rfay        2226    2198  0 16:36 ?        00:00:00 /usr/bin/php /var/www/html/artisan queue:work --sleep=3 --tries=3
```

Looks like exactly what's expected.

2024-05-13 03:40 UTC, tyler36 commented
> The grep should have 2>/dev/null on it probably.

Updated.

2024-05-13 16:41 UTC, rfay approved these changes
Seems to be working great to me! Thanks!

2024-05-14 00:02 UTC, merged